version: '3'

services:
  postgres:
    container_name: bar_db
    restart: always
    image: postgres:15
    environment:
      POSTGRES_USER: bar_user
      POSTGRES_PASSWORD: bar_pass
      POSTGRES_DB: bar_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
